steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['install']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'function-beejaDB','--entry-point','app','--runtime', 'nodejs12','--trigger-http','--allow-unauthenticated']