steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'function/dir/from/repo/root'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run',]
  dir: 'function/dir/from/repo/root'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'hello-world-0_1_4','--entry-point','app','--runtime', 'nodejs10','--trigger-http','--allow-unauthenticated']
  dir: 'function/dir/from/repo/root'