steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'function/dir/from/repo/root'
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['test']
#   dir: 'function/dir/from/repo/root'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', '[function-4]','[--trigger-http]','--runtime', '[nodejs10]','--entry-point','[app]']
  dir: 'function/dir/from/repo/root'