steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'function/dir/from/repo/root'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'function/dir/from/repo/root'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions-9', 'deploy', '[backendcicd-12345]','[https://us-central1-absolute-shell-307821.cloudfunctions.net/backendcicd-12345]','--runtime', '[nodejs10]','--entry-point','[app]']
  dir: 'function/dir/from/repo/root'